# Example Automations
# This file contains example automation rules for Home Assistant
# Customize and expand based on your needs

# Example: Welcome home automation
- id: 'welcome_home'
  alias: Welcome Home
  description: Turn on lights when arriving home after sunset
  trigger:
    - platform: state
      entity_id: person.your_name
      to: 'home'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-00:30:00"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hallway
      data:
        brightness_pct: 80
        color_temp: 400
    - service: notify.mobile_app
      data:
        message: "Welcome home! Lights have been turned on."

# Example: Good night routine
- id: 'good_night'
  alias: Good Night Routine
  description: Turn off all lights at bedtime
  trigger:
    - platform: time
      at: "23:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: light.turn_off
      target:
        entity_id: all
    - service: switch.turn_off
      target:
        entity_id: switch.living_room_tv

# Example: Motion-activated lighting
- id: 'motion_light'
  alias: Motion Activated Light
  description: Turn on light when motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.hallway_light_level
      below: 50
  action:
    - service: light.turn_on
      target:
        entity_id: light.hallway
      data:
        brightness_pct: 60
    - delay: '00:05:00'
    - service: light.turn_off
      target:
        entity_id: light.hallway

# Example: Low battery notification
- id: 'low_battery_notification'
  alias: Low Battery Notification
  description: Notify when device battery is low
  trigger:
    - platform: numeric_state
      entity_id: 
        - sensor.motion_sensor_battery
        - sensor.door_sensor_battery
        - sensor.temperature_sensor_battery
      below: 20
  action:
    - service: notify.mobile_app
      data:
        title: "Low Battery Warning"
        message: "{{ trigger.to_state.attributes.friendly_name }} battery is at {{ trigger.to_state.state }}%"

# Example: Temperature alert
- id: 'temperature_alert'
  alias: High Temperature Alert
  description: Alert when temperature is too high
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_temperature
      above: 26
      for:
        minutes: 10
  action:
    - service: notify.mobile_app
      data:
        title: "Temperature Alert"
        message: "Living room temperature is {{ states('sensor.living_room_temperature') }}°C"
